//* USER
export const USER_LOADED = "USER_LOADED";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const REQUEST_USER_LOG_IN = "REQUEST_USER_LOG_IN";

//* APP_STATE
export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_ERROR";
export const SET_DANGER_ERROR = "SET_DANGER_ERROR";
export const SET_WARNING_ERROR = "SET_WARNING_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

//* DOCUMENTS
export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS";
export const DOCUMENTS_LOADED = "DOCUMENTS_LOADED";
export const CHANGE_BOX = "CHANGE_BOX";
export const GET_REGIONS = "GET_REGIONS";
export const DOCUMENTS_COUNT_LOADED = "DOCUMENTS_COUNT_LOADED";
export const CREATE_DOCUMENT = "CREATE_DOCUMENT";

//* DOCUMENT INTERACTIONS
export const ACCEPT_DOCUMENT = "ACCEPT_DOCUMENT";
export const REJECT_DOCUMENT = "REJECT_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
