
//* USER
export const USER_LOADED = 'USER_LOADED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const REQUEST_USER_LOG_IN = 'REQUEST_USER_LOG_IN';

//* APP_STATE
export const SET_SUCCESS_ERROR = 'SET_SUCCESS_ERROR';
export const SET_DANGER_ERROR = 'SET_DANGER_ERROR';
export const SET_WARNING_ERROR = 'SET_WARNING_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

//* DOCUMENTS
export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS';
export const DOCUMENTS_LOADED = 'DOCUMENTS_LOADED'